import {
    LayoutDashboard,
    Users,
    ShoppingBag,
    ShoppingCart,
    FileText,
    UserCheck,
    UserPlus,
    List,
    Wallet,
    Gift,
    TrendingUp,
    CreditCard,
    Trophy,
    User,
    ClipboardList,
    Book,
    Archive,
    Package,
    Settings,
    ListTodo,
    DollarSign,
    Phone,
    Calendar,
    Briefcase,
    Megaphone,
    Globe,
    MessageCircle, // Chat
    RefreshCw,     // Sync
    FlaskConical,   // R&D
    Truck,          // Shipper
    Calculator,    // Accountant
    ClipboardCheck, // Sale Admin
    Video,         // Livestream
    ToggleLeft,     // Role Switch
    ArrowRightLeft, // Accountant Reconciliation
    Zap,            // Automation
    Gamepad2,
    Sparkles,       // Poster Studio
    MapPin,         // Sales GT
    Camera,         // Media Creator
    FolderOpen,     // Media Library
    Wrench,         // Equipment
    FileInput,      // Brief
    Heart,
} from "lucide-react";
import { MODULES } from '@/modules/registry';

// FEATURE FLAGS
const USE_NEW_MODULE_LEADS = process.env.NEXT_PUBLIC_NEW_MODULE_LEADS === '1';
const USE_NEW_MODULE_ORDERS = process.env.NEXT_PUBLIC_NEW_MODULE_ORDERS === '1';

const PATH_LEADS = USE_NEW_MODULE_LEADS ? MODULES.leads.path : "/crm";
const PATH_ORDERS_TELESALES = USE_NEW_MODULE_ORDERS ? MODULES.orders.path : "/telesales/orders";
const PATH_ORDERS_ADMIN = USE_NEW_MODULE_ORDERS ? MODULES.orders.path : "/admin/orders";
const PATH_ORDERS_SALES = USE_NEW_MODULE_ORDERS ? MODULES.orders.path : "/sales/orders";

export const ROLES = {
    ADMIN: "admin",
    CUSTOMER: "customer",
    SALES: "sales",
    CTV: "ctv",
    TELESALES: "telesales",
    RECRUITER: "recruiter",
    WAREHOUSE: "warehouse",
    MARKETING: "marketing",
    ECOMMERCE: "ecommerce",
    RND: "rnd",
    SHIPPER: "shipper",
    ACCOUNTANT: "accountant",
    SALE_ADMIN: "sale_admin",
    LIVESTREAM: "livestream",
    SALES_GT: "sales_gt",
    MEDIA_CREATOR: "media_creator",
} as const;

export const NAV_ITEMS = {
    [ROLES.LIVESTREAM]: [
        { label: "Tổng quan Live", href: "/livestream", icon: LayoutDashboard },
        { label: "Màn hình Chốt đơn", href: "/livestream/live", icon: Video },
        { label: "Đơn hàng Live", href: "/livestream/orders", icon: ShoppingCart },
        { label: "Sản phẩm Live", href: "/livestream/products", icon: Package },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Văn hóa doanh nghiệp", href: "/culture", icon: Heart },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: Book },
    ],
    [ROLES.SALE_ADMIN]: [
        { label: "Tổng quan Admin", href: "/sale-admin", icon: LayoutDashboard },
        { label: "CRM", href: PATH_LEADS, icon: TrendingUp },
        { label: "Khách hàng", href: "/sale-admin/customers", icon: Users },
        { label: "Quản lý Đơn hàng", href: "/sale-admin/orders", icon: ClipboardCheck },
        { label: "Báo giá & Hợp đồng", href: "/sale-admin/quotes", icon: FileText },
        { label: "Hỗ trợ Sales", href: "/sale-admin/support", icon: Users },
        { label: "Sản phẩm", href: "/sale-admin/products", icon: Package },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Việc cần làm", href: "/sale-admin/tasks", icon: ListTodo },
        { label: "Văn hóa doanh nghiệp", href: "/culture", icon: Heart },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: Book },
    ],
    [ROLES.ACCOUNTANT]: [
        { label: "Tổng quan Kế toán", href: "/accountant", icon: LayoutDashboard },
        { label: "Việc cần làm", href: "/accountant/tasks", icon: ListTodo },
        { label: "Quản lý Đơn hàng", href: "/accountant/orders", icon: FileText },
        { label: "Quản lý Doanh thu", href: "/accountant/revenue", icon: TrendingUp },
        { label: "Quản lý Chi phí", href: "/accountant/expenses", icon: CreditCard },
        { label: "Quản lý Nhập hàng", href: "/accountant/purchases", icon: ShoppingCart },
        { label: "Đối soát Ngân hàng", href: "/accountant/reconciliation", icon: ArrowRightLeft },
        { label: "Lương & Hoa hồng", href: "/accountant/payroll", icon: DollarSign },
        { label: "Quản lý Công nợ", href: "/accountant/debts", icon: Wallet },
        { label: "Danh mục MISA", href: "/accountant/master-data", icon: Book },
        { label: "Sản phẩm", href: "/accountant/products", icon: Package },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Xếp lịch làm việc", href: "/hr/scheduling", icon: Calendar },
        { label: "Góc Giải Trí", href: "/entertainment", icon: Gamepad2 },
        { label: "Văn hóa doanh nghiệp", href: "/culture", icon: Heart },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: Book },
    ],
    [ROLES.SHIPPER]: [
        { label: "Tổng quan Vận chuyển", href: "/shipper", icon: LayoutDashboard },
        { label: "Đơn cần giao", href: "/shipper/deliveries", icon: Truck },
        { label: "Ví & COD", href: "/shipper/wallet", icon: Wallet },
        { label: "Lịch sử", href: "/shipper/history", icon: ClipboardList },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Văn hóa doanh nghiệp", href: "/culture", icon: Heart },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: FileText },
    ],
    [ROLES.RND]: [
        { label: "Tổng quan R&D", href: "/rnd", icon: LayoutDashboard },
        { label: "Dự án nghiên cứu", href: "/rnd/projects", icon: FlaskConical },
        { label: "Quản lý mẫu", href: "/rnd/samples", icon: Package },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Văn hóa doanh nghiệp", href: "/culture", icon: Heart },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: FileText },
        { label: "Việc cần làm", href: "/tasks", icon: ListTodo },
    ],
    [ROLES.ECOMMERCE]: [
        { label: "Tổng quan TMĐT", href: "/ecommerce", icon: LayoutDashboard },
        { label: "Đơn hàng đa kênh", href: "/ecommerce/orders", icon: ShoppingCart },
        { label: "Chat đa kênh", href: "/ecommerce/chat", icon: MessageCircle },
        { label: "Đối soát tài chính", href: "/ecommerce/finance", icon: DollarSign },
        { label: "Liên kết kho & SP", href: "/ecommerce/products", icon: RefreshCw },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Văn hóa doanh nghiệp", href: "/culture", icon: Heart },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: FileText },
        { label: "Việc cần làm", href: "/tasks", icon: ListTodo },
    ],
    [ROLES.ADMIN]: [
        { label: "Tổng quan", href: "/admin", icon: LayoutDashboard },
        { label: "CRM", href: PATH_LEADS, icon: TrendingUp },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Việc cần làm", href: "/admin/tasks", icon: ListTodo },
        { label: "Đơn hàng", href: PATH_ORDERS_ADMIN, icon: FileText },
        { label: "Người dùng", href: "/admin/users", icon: Users },
        { label: "Khách hàng", href: "/admin/customers", icon: UserCheck },
        { label: "Sản phẩm", href: "/admin/products", icon: Package },
        { label: "Báo cáo Telesales", href: "/admin/telesales/earnings", icon: Phone },
        { label: "Hiệu suất CTV", href: "/admin/ctv", icon: TrendingUp },
        { label: "Báo cáo Sales GT", href: "/admin/gt-reports", icon: MapPin },
        { label: "Báo cáo Media", href: "/admin/media-reports", icon: Camera },
        { label: "Lịch quay & Brief", href: "/admin/media-briefs", icon: FileInput },
        { label: "Dự án Media", href: "/admin/media-projects", icon: ClipboardList },
        { label: "Thiết bị Media", href: "/admin/media-equipment", icon: Wrench },
        { label: "Thư viện Media", href: "/admin/media-library", icon: FolderOpen },
        { label: "------------", href: "#", icon: List }, // Separator
        { label: "Ứng viên (Tuyển dụng)", href: "/recruitment/candidates", icon: Users },
        { label: "Hiệu quả Tuyển dụng", href: "/recruitment/performance", icon: Trophy },
        { label: "Báo cáo Tuyển dụng", href: "/recruitment/reports", icon: ClipboardList },
        { label: "Mối quan hệ", href: "/recruitment/networking", icon: UserPlus },
        { label: "Nền tảng & Tài nguyên", href: "/recruitment/platforms", icon: Globe },
        { label: "------------", href: "#", icon: List }, // Separator
        { label: "Hồ sơ Nhân sự", href: "/hr/directory", icon: Users },
        { label: "------------", href: "#", icon: List }, // Separator
        { label: "Góc Giải Trí", href: "/entertainment", icon: Gamepad2 },
        { label: "Lương & Thưởng", href: "/admin/payroll", icon: DollarSign },
        { label: "Cài đặt", href: "/admin/settings", icon: Settings },
        { label: "Văn hóa doanh nghiệp", href: "/culture", icon: Heart },
        { label: "Tài liệu", href: "/documents", icon: FileText },
        { label: "Đổi Role (Debug)", href: "/debug-role", icon: ToggleLeft },
    ],
    [ROLES.CUSTOMER]: [
        { label: "Trang chủ", href: "/customer", icon: LayoutDashboard },
        { label: "Đặt hàng", href: "/customer/products", icon: Package },
        { label: "Đơn hàng", href: "/customer/orders", icon: ShoppingCart },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: FileText },
    ],
    [ROLES.SALES]: [
        { label: "Tổng quan Sales", href: "/sales", icon: LayoutDashboard },
        { label: "CRM", href: PATH_LEADS, icon: TrendingUp },
        { label: "Khách hàng", href: "/sales/customers", icon: Users },
        { label: "Đơn hàng", href: PATH_ORDERS_SALES, icon: ShoppingCart },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Xếp lịch làm việc", href: "/hr/scheduling", icon: Calendar },
        { label: "Góc Giải Trí", href: "/entertainment", icon: Gamepad2 },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: FileText },
    ],
    [ROLES.CTV]: [
        { label: "Tổng quan CTV", href: "/ctv", icon: LayoutDashboard },
        { label: "Tạo đơn hàng", href: "/ctv/create-order", icon: ShoppingCart },
        { label: "Đơn hàng của tôi", href: "/ctv/orders", icon: Package },
        { label: "Khách hàng của tôi", href: "/ctv/customers", icon: Users },
        { label: "Lead & Tiềm năng", href: "/ctv/leads", icon: UserPlus },
        { label: "Việc cần làm", href: "/ctv/tasks", icon: ListTodo },
        { label: "Hoa hồng & Ví", href: "/ctv/wallet", icon: DollarSign },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Xếp lịch làm việc", href: "/hr/scheduling", icon: Calendar },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: FileText },
    ],
    [ROLES.TELESALES]: [
        { label: "Tổng quan", href: "/telesales", icon: LayoutDashboard },
        { label: "CRM", href: PATH_LEADS, icon: TrendingUp },
        { label: "Lịch làm việc", href: "/telesales/schedule", icon: Calendar },
        { label: "Việc cần làm", href: "/telesales/tasks", icon: ListTodo },
        { label: "Tạo đơn hàng", href: "/telesales/create-order", icon: ShoppingCart },
        { label: "Đơn hàng", href: PATH_ORDERS_TELESALES, icon: Package },
        { label: "Khách hàng", href: "/telesales/customers", icon: Users },
        { label: "Nhóm FB đăng bài", href: "/telesales/fb-groups", icon: Globe },
        { label: "Thu nhập & KPI", href: "/telesales/earnings", icon: DollarSign },
        { label: "Quy định & Chính sách", href: "/telesales/rules", icon: Book },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Xếp lịch làm việc", href: "/hr/scheduling", icon: Calendar },
        { label: "Góc Giải Trí", href: "/entertainment", icon: Gamepad2 },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: FileText },
    ],
    [ROLES.RECRUITER]: [
        { label: "Tổng quan Tuyển dụng", href: "/recruitment", icon: LayoutDashboard },
        { label: "Báo cáo ngày", href: "/recruitment/daily", icon: ClipboardList },
        { label: "Ứng viên (Kanban)", href: "/recruitment/candidates", icon: Users },
        { label: "Lịch phỏng vấn", href: "/recruitment/interviews", icon: Calendar },
        { label: "Tin tuyển dụng", href: "/recruitment/jobs", icon: Briefcase },
        { label: "Hiệu quả (Social)", href: "/recruitment/performance", icon: TrendingUp },
        { label: "Mối quan hệ", href: "/recruitment/networking", icon: UserPlus },
        { label: "Nền tảng & Tài nguyên", href: "/recruitment/platforms", icon: Globe },
        { label: "Hồ sơ Nhân sự", href: "/hr/directory", icon: Users },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Việc cần làm", href: "/tasks", icon: ListTodo },
        { label: "Thu nhập & KPI", href: "/recruitment/earnings", icon: DollarSign },
        { label: "Quy định & Chính sách", href: "/recruitment/rules", icon: Book },
        { label: "Hồ sơ công ty", href: "/recruitment/settings", icon: Settings },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Góc Giải Trí", href: "/entertainment", icon: Gamepad2 },
        { label: "Tài liệu", href: "/documents", icon: FileText },
    ],
    [ROLES.WAREHOUSE]: [
        { label: "Tổng quan Kho", href: "/warehouse", icon: LayoutDashboard },
        { label: "Quản lý Đơn hàng", href: "/warehouse/orders", icon: ClipboardCheck },
        { label: "Xử lý Đơn hàng", href: "/warehouse/fulfillment", icon: ClipboardCheck },
        { label: "Quản lý tồn kho", href: "/warehouse/inventory", icon: Archive },
        { label: "Kiểm kê Kho", href: "/warehouse/audit", icon: Archive },
        { label: "Sản phẩm", href: "/warehouse/products", icon: Package },
        { label: "Xếp lịch làm việc", href: "/hr/scheduling", icon: Calendar },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Góc Giải Trí", href: "/entertainment", icon: Gamepad2 },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: FileText },
        { label: "Việc cần làm", href: "/tasks", icon: ListTodo },
    ],
    [ROLES.MARKETING]: [
        { label: "Tổng quan Marketing", href: "/marketing", icon: LayoutDashboard },
        { label: "Hộp thư (Inbox)", href: "/marketing/inbox", icon: MessageCircle },
        { label: "Chiến dịch", href: "/marketing/campaigns", icon: Megaphone },
        { label: "Leads", href: "/marketing/leads", icon: Users },
        { label: "Content & Lịch", href: "/marketing/content", icon: Calendar },
        { label: "Quét Data", href: "/marketing/scraper", icon: Globe },
        { label: "Tự động hóa", href: "/marketing/automation", icon: Zap },
        { label: "AI Poster Studio", href: "/marketing/poster-studio", icon: Sparkles },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Xếp lịch làm việc", href: "/hr/scheduling", icon: Calendar },
        { label: "Góc Giải Trí", href: "/entertainment", icon: Gamepad2 },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: FileText },
        { label: "Việc cần làm", href: "/tasks", icon: ListTodo },
    ],
    [ROLES.SALES_GT]: [
        { label: "Tổng quan GT", href: "/sales-gt", icon: LayoutDashboard },
        { label: "Điểm bán", href: "/sales-gt/outlets", icon: MapPin },
        { label: "Check-in", href: "/sales-gt/checkin", icon: MapPin },
        { label: "Tạo đơn hàng", href: "/sales-gt/create-order", icon: ShoppingCart },
        { label: "Đơn hàng", href: "/sales-gt/orders", icon: Package },
        { label: "Khách hàng", href: "/sales-gt/customers", icon: Users },
        { label: "Tuyến bán hàng", href: "/sales-gt/routes", icon: List },
        { label: "Báo cáo", href: "/sales-gt/reports", icon: TrendingUp },
        { label: "Lịch làm việc", href: "/sales-gt/schedule", icon: Calendar },
        { label: "Việc cần làm", href: "/sales-gt/tasks", icon: ListTodo },
        { label: "Thu nhập & KPI", href: "/sales-gt/earnings", icon: DollarSign },
        { label: "Quy định & Chính sách", href: "/sales-gt/rules", icon: Book },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Xếp lịch làm việc", href: "/hr/scheduling", icon: Calendar },
        { label: "Góc Giải Trí", href: "/entertainment", icon: Gamepad2 },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: Book },
    ],
    [ROLES.MEDIA_CREATOR]: [
        { label: "Tổng quan", href: "/media", icon: LayoutDashboard },
        { label: "Brief / Yêu cầu", href: "/media/briefs", icon: FileInput },
        { label: "Thư viện Media", href: "/media/library", icon: FolderOpen },
        { label: "Dự án", href: "/media/projects", icon: ClipboardList },
        { label: "Thiết bị", href: "/media/equipment", icon: Wrench },
        { label: "Việc cần làm", href: "/media/tasks", icon: ListTodo },
        { label: "Thu nhập & KPI", href: "/media/earnings", icon: DollarSign },
        { label: "Quy định & Chính sách", href: "/media/rules", icon: Book },
        { label: "Tin nhắn nội bộ", href: "/chat", icon: MessageCircle },
        { label: "Xếp lịch làm việc", href: "/hr/scheduling", icon: Calendar },
        { label: "Lịch làm việc", href: "/media/schedule", icon: Calendar },
        { label: "Góc Giải Trí", href: "/entertainment", icon: Gamepad2 },
        { label: "Sự kiện", href: "/events", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: Book },
    ],
};
