import {
    LayoutDashboard,
    Users,
    ShoppingBag,
    ShoppingCart,
    FileText,
    UserCheck,
    UserPlus,
    List,
    Wallet,
    Gift,
    TrendingUp,
    CreditCard,
    Trophy,
    User,
    ClipboardList,
    Book,
    Archive,
    Package,
    Settings,
    ListTodo,
    DollarSign,
    Phone,
    Calendar,
    Briefcase,
    Megaphone,
    Globe,
    MessageCircle, // Chat
    RefreshCw,     // Sync
    FlaskConical,   // R&D
    Truck,          // Shipper
    Calculator,    // Accountant
    ClipboardCheck, // Sale Admin
    Video,         // Livestream
    ToggleLeft,     // Role Switch
    ArrowRightLeft, // Accountant Reconciliation
} from "lucide-react";

export const ROLES = {
    ADMIN: "admin",
    CUSTOMER: "customer",
    SALES: "sales",
    CTV: "ctv",
    TELESALES: "telesales",
    RECRUITER: "recruiter",
    WAREHOUSE: "warehouse",
    MARKETING: "marketing",
    ECOMMERCE: "ecommerce",
    RND: "rnd",
    SHIPPER: "shipper",
    ACCOUNTANT: "accountant",
    SALE_ADMIN: "sale_admin",
    LIVESTREAM: "livestream",
} as const;

export const NAV_ITEMS = {
    [ROLES.LIVESTREAM]: [
        { label: "Tổng quan Live", href: "/livestream", icon: LayoutDashboard },
        { label: "Màn hình Chốt đơn", href: "/livestream/live", icon: Video },
        { label: "Đơn hàng Live", href: "/livestream/orders", icon: ShoppingCart },
        { label: "Sản phẩm Live", href: "/livestream/products", icon: Package },
        { label: "Tài liệu", href: "/documents", icon: Book },
    ],
    [ROLES.SALE_ADMIN]: [
        { label: "Tổng quan Admin", href: "/sale-admin", icon: LayoutDashboard },
        { label: "CRM", href: "/crm", icon: TrendingUp },
        { label: "Khách hàng", href: "/sale-admin/customers", icon: Users },
        { label: "Quản lý Đơn hàng", href: "/sale-admin/orders", icon: ClipboardCheck },
        { label: "Báo giá & Hợp đồng", href: "/sale-admin/quotes", icon: FileText },
        { label: "Hỗ trợ Sales", href: "/sale-admin/support", icon: Users },
        { label: "Tài liệu", href: "/documents", icon: Book },
    ],
    [ROLES.ACCOUNTANT]: [
        { label: "Tổng quan Kế toán", href: "/accountant", icon: LayoutDashboard },
        { label: "Việc cần làm", href: "/accountant/tasks", icon: ListTodo },
        { label: "Quản lý Doanh thu", href: "/accountant/revenue", icon: TrendingUp },
        { label: "Quản lý Chi phí", href: "/accountant/expenses", icon: CreditCard },
        { label: "Quản lý Nhập hàng", href: "/accountant/purchases", icon: ShoppingCart },
        { label: "Đối soát Ngân hàng", href: "/accountant/reconciliation", icon: ArrowRightLeft },
        { label: "Lương & Hoa hồng", href: "/accountant/payroll", icon: DollarSign },
        { label: "Quản lý Công nợ", href: "/accountant/debts", icon: Wallet },
        { label: "Danh mục MISA", href: "/accountant/master-data", icon: Book },
        { label: "Tài liệu", href: "/documents", icon: FileText },
    ],
    [ROLES.SHIPPER]: [
        { label: "Tổng quan Vận chuyển", href: "/shipper", icon: LayoutDashboard },
        { label: "Đơn cần giao", href: "/shipper/deliveries", icon: Truck },
        { label: "Ví & COD", href: "/shipper/wallet", icon: Wallet },
        { label: "Lịch sử", href: "/shipper/history", icon: ClipboardList },
        { label: "Tài liệu", href: "/documents", icon: FileText },
    ],
    [ROLES.RND]: [
        { label: "Tổng quan R&D", href: "/rnd", icon: LayoutDashboard },
        { label: "Dự án nghiên cứu", href: "/rnd/projects", icon: FlaskConical },
        { label: "Quản lý mẫu", href: "/rnd/samples", icon: Package },
        { label: "Tài liệu", href: "/documents", icon: FileText },
        { label: "Việc cần làm", href: "/tasks", icon: ListTodo },
    ],
    [ROLES.ECOMMERCE]: [
        { label: "Tổng quan TMĐT", href: "/ecommerce", icon: LayoutDashboard },
        { label: "Đơn hàng đa kênh", href: "/ecommerce/orders", icon: ShoppingCart },
        { label: "Chat đa kênh", href: "/ecommerce/chat", icon: MessageCircle },
        { label: "Đối soát tài chính", href: "/ecommerce/finance", icon: DollarSign },
        { label: "Liên kết kho & SP", href: "/ecommerce/products", icon: RefreshCw },
        { label: "Tài liệu", href: "/documents", icon: FileText },
        { label: "Việc cần làm", href: "/tasks", icon: ListTodo },
    ],
    [ROLES.ADMIN]: [
        { label: "Tổng quan", href: "/admin", icon: LayoutDashboard },
        { label: "CRM", href: "/crm", icon: TrendingUp },
        { label: "Việc cần làm", href: "/admin/tasks", icon: ListTodo },
        { label: "Đơn hàng", href: "/admin/orders", icon: FileText },
        { label: "Người dùng", href: "/admin/users", icon: Users },
        { label: "Khách hàng", href: "/admin/customers", icon: UserCheck },
        { label: "Sản phẩm", href: "/admin/products", icon: Package },
        { label: "Hiệu suất CTV", href: "/admin/ctv", icon: TrendingUp },
        { label: "Lương & Thưởng", href: "/admin/payroll", icon: DollarSign },
        { label: "Cài đặt", href: "/admin/settings", icon: Settings },
        { label: "Tài liệu", href: "/documents", icon: FileText },
        { label: "Đổi Role (Debug)", href: "/debug-role", icon: ToggleLeft },
    ],
    [ROLES.CUSTOMER]: [
        { label: "Trang chủ", href: "/customer", icon: LayoutDashboard },
        { label: "Đặt hàng", href: "/customer/products", icon: Package },
        { label: "Đơn hàng", href: "/customer/orders", icon: ShoppingCart },
        { label: "Tài liệu", href: "/documents", icon: FileText },
    ],
    [ROLES.SALES]: [
        { label: "Tổng quan Sales", href: "/sales", icon: LayoutDashboard },
        { label: "CRM", href: "/crm", icon: TrendingUp },
        { label: "Khách hàng", href: "/sales/customers", icon: Users },
        { label: "Đơn hàng", href: "/sales/orders", icon: ShoppingCart },
        { label: "Tài liệu", href: "/documents", icon: FileText },
    ],
    [ROLES.CTV]: [
        { label: "Tổng quan CTV", href: "/ctv", icon: LayoutDashboard },
        { label: "Tạo đơn hàng", href: "/ctv/create-order", icon: ShoppingCart },
        { label: "Đơn hàng của tôi", href: "/ctv/orders", icon: Package },
        { label: "Khách hàng của tôi", href: "/ctv/customers", icon: Users },
        { label: "Lead & Tiềm năng", href: "/ctv/leads", icon: UserPlus },
        { label: "Việc cần làm", href: "/ctv/tasks", icon: ListTodo },
        { label: "Hoa hồng & Ví", href: "/ctv/wallet", icon: DollarSign },
        { label: "Tài liệu", href: "/documents", icon: FileText },
    ],
    [ROLES.TELESALES]: [
        { label: "Tổng quan", href: "/telesales", icon: LayoutDashboard },
        { label: "CRM", href: "/crm", icon: TrendingUp },
        { label: "Việc cần làm", href: "/telesales/tasks", icon: ListTodo },
        { label: "Tạo đơn hàng", href: "/telesales/create-order", icon: ShoppingCart },
        { label: "Đơn hàng", href: "/telesales/orders", icon: Package },
        { label: "Khách hàng", href: "/telesales/customers", icon: Users },
        { label: "Thu nhập & KPI", href: "/telesales/earnings", icon: DollarSign },
        { label: "Quy định & Chính sách", href: "/telesales/rules", icon: Book },
        { label: "Tài liệu", href: "/documents", icon: FileText },
    ],
    [ROLES.RECRUITER]: [
        { label: "Tổng quan Tuyển dụng", href: "/recruitment", icon: LayoutDashboard },
        { label: "Ứng viên (Kanban)", href: "/recruitment/candidates", icon: Users },
        { label: "Lịch phỏng vấn", href: "/recruitment/interviews", icon: Calendar },
        { label: "Tin tuyển dụng", href: "/recruitment/jobs", icon: Briefcase },
        { label: "Việc cần làm", href: "/tasks", icon: ListTodo },
        { label: "Tài liệu", href: "/documents", icon: FileText },
    ],
    [ROLES.WAREHOUSE]: [
        { label: "Tổng quan Kho", href: "/warehouse", icon: LayoutDashboard },
        { label: "Xử lý Đơn hàng", href: "/warehouse/fulfillment", icon: ClipboardCheck },
        { label: "Quản lý tồn kho", href: "/warehouse/inventory", icon: Archive },
        { label: "Kiểm kê Kho", href: "/warehouse/audit", icon: Archive },
        { label: "Tài liệu", href: "/documents", icon: FileText },
        { label: "Việc cần làm", href: "/tasks", icon: ListTodo },
    ],
    [ROLES.MARKETING]: [
        { label: "Tổng quan Marketing", href: "/marketing", icon: LayoutDashboard },
        { label: "Chiến dịch", href: "/marketing/campaigns", icon: Megaphone },
        { label: "Content & Lịch", href: "/marketing/content", icon: Calendar },
        { label: "Tài liệu", href: "/documents", icon: FileText },
        { label: "Việc cần làm", href: "/tasks", icon: ListTodo },
    ],
};
