import { Region } from "./usersStore";

export const PROVINCES_VN = [
    "Hà Nội",
    "TP.HCM",
    "Đà Nẵng",
    "Hải Phòng",
    "Cần Thơ",
    "Nghệ An",
    "Thanh Hóa",
    "Quảng Ninh",
    "Bắc Ninh",
    "Hải Dương",
    "Hưng Yên",
    "Nam Định",
    "Ninh Bình",
    "Thái Bình",
    "Vĩnh Phúc",
    "Bình Dương",
    "Đồng Nai",
    "Long An",
    "Bình Phước",
    "Tây Ninh",
    "Bà Rịa - Vũng Tàu",
    "Tiền Giang",
    "Bến Tre",
    "Vĩnh Long",
    "Trà Vinh",
    "Đồng Tháp",
    "An Giang",
    "Kiên Giang",
    "Hậu Giang",
    "Sóc Trăng",
    "Bạc Liêu",
    "Cà Mau",
    "Khánh Hòa",
    "Lâm Đồng",
    "Bình Thuận",
    "Ninh Thuận",
    "Phú Yên",
    "Thừa Thiên Huế",
    "Quảng Nam",
    "Quảng Ngãi",
    "Bình Định",
    "Gia Lai",
    "Kon Tum",
    "Đắk Lắk",
    "Đắk Nông",
    "Unknown",
];

export const REGION_BY_PROVINCE: Record<string, Region> = {
    "Hà Nội": "North",
    "Hải Phòng": "North",
    "Quảng Ninh": "North",
    "Bắc Ninh": "North",
    "Hải Dương": "North",
    "Hưng Yên": "North",
    "Nam Định": "North",
    "Ninh Bình": "North",
    "Thái Bình": "North",
    "Vĩnh Phúc": "North",
    "Nghệ An": "North",
    "Thanh Hóa": "North",

    "Đà Nẵng": "Central",
    "Thừa Thiên Huế": "Central",
    "Quảng Nam": "Central",
    "Quảng Ngãi": "Central",
    "Bình Định": "Central",
    "Phú Yên": "Central",
    "Khánh Hòa": "Central",
    "Ninh Thuận": "Central",
    "Bình Thuận": "Central",
    "Gia Lai": "Central",
    "Kon Tum": "Central",
    "Đắk Lắk": "Central",
    "Đắk Nông": "Central",
    "Lâm Đồng": "Central",

    "TP.HCM": "South",
    "Cần Thơ": "South",
    "Bình Dương": "South",
    "Đồng Nai": "South",
    "Long An": "South",
    "Bình Phước": "South",
    "Tây Ninh": "South",
    "Bà Rịa - Vũng Tàu": "South",
    "Tiền Giang": "South",
    "Bến Tre": "South",
    "Vĩnh Long": "South",
    "Trà Vinh": "South",
    "Đồng Tháp": "South",
    "An Giang": "South",
    "Kiên Giang": "South",
    "Hậu Giang": "South",
    "Sóc Trăng": "South",
    "Bạc Liêu": "South",
    "Cà Mau": "South",

    "Unknown": "Other",
};

export function getRegionFromProvince(province: string): Region {
    return REGION_BY_PROVINCE[province] || "Other";
}

export const REGION_LABELS: Record<Region, string> = {
    North: "Miền Bắc",
    Central: "Miền Trung",
    South: "Miền Nam",
    Other: "Khác",
};
