export const PROVINCES = [
    { code: '01', name: 'Hà Nội' },
    { code: '79', name: 'Hồ Chí Minh' },
    { code: '48', name: 'Đà Nẵng' },
    { code: '31', name: 'Hải Phòng' },
    { code: '92', name: 'Cần Thơ' },
    { code: '27', name: 'Bắc Ninh' },
    { code: '26', name: 'Vĩnh Phúc' },
    { code: '25', name: 'Phú Thọ' },
    { code: '22', name: 'Quảng Ninh' },
    { code: '24', name: 'Bắc Giang' },
    { code: '19', name: 'Thái Nguyên' },
    { code: '33', name: 'Hưng Yên' },
    { code: '35', name: 'Hà Nam' },
    { code: '36', name: 'Nam Định' },
    { code: '37', name: 'Ninh Bình' },
    { code: '40', name: 'Nghệ An' },
    { code: '75', name: 'Đồng Nai' },
    { code: '74', name: 'Bình Dương' },
    { code: '72', name: 'Tây Ninh' },
    { code: '77', name: 'Bà Rịa - Vũng Tàu' }
].sort((a, b) => a.name.localeCompare(b.name));

// Sample districts for major cities (Full list would be too long, using sample)
// Sample districts for major cities and provinces
export const DISTRICTS: Record<string, { code: string, name: string }[]> = {
    '01': [ // Hà Nội
        { code: '001', name: 'Ba Đình' },
        { code: '002', name: 'Hoàn Kiếm' },
        { code: '003', name: 'Tây Hồ' },
        { code: '004', name: 'Long Biên' },
        { code: '005', name: 'Cầu Giấy' },
        { code: '006', name: 'Đống Đa' },
        { code: '007', name: 'Hai Bà Trưng' },
        { code: '008', name: 'Hoàng Mai' },
        { code: '009', name: 'Thanh Xuân' },
        { code: '016', name: 'Bắc Từ Liêm' },
        { code: '019', name: 'Nam Từ Liêm' },
        { code: '018', name: 'Hà Đông' },
        { code: '017', name: 'Sơn Tây' },
        { code: '020', name: 'Ba Vì' },
        { code: '021', name: 'Phúc Thọ' },
        { code: '022', name: 'Đan Phượng' },
        { code: '023', name: 'Hoài Đức' },
        { code: '024', name: 'Quốc Oai' },
        { code: '025', name: 'Thạch Thất' },
        { code: '026', name: 'Chương Mỹ' },
        { code: '027', name: 'Thanh Oai' },
        { code: '028', name: 'Thường Tín' },
        { code: '029', name: 'Phú Xuyên' },
        { code: '030', name: 'Ứng Hòa' },
        { code: '031', name: 'Mỹ Đức' },
        { code: '250', name: 'Mê Linh' },
        { code: '010', name: 'Sóc Sơn' },
        { code: '011', name: 'Đông Anh' },
        { code: '012', name: 'Gia Lâm' },
        { code: '013', name: 'Thanh Trì' }
    ],
    '79': [ // HCM
        { code: '760', name: 'Quận 1' },
        { code: '761', name: 'Quận 12' },
        { code: '769', name: 'Thủ Đức' },
        { code: '770', name: 'Gò Vấp' },
        { code: '765', name: 'Bình Thạnh' },
        { code: '766', name: 'Tân Bình' },
        { code: '767', name: 'Tân Phú' },
        { code: '768', name: 'Phú Nhuận' },
        { code: '771', name: 'Bình Tân' },
        { code: '772', name: 'Củ Chi' },
        { code: '773', name: 'Hóc Môn' },
        { code: '774', name: 'Bình Chánh' },
        { code: '775', name: 'Nhà Bè' },
        { code: '776', name: 'Cần Giờ' },
        { code: '762', name: 'Quận 3' },
        { code: '763', name: 'Quận 5' },
        { code: '764', name: 'Quận 6' },
        { code: '777', name: 'Quận 8' },
        { code: '778', name: 'Quận 10' },
        { code: '780', name: 'Quận 11' },
        { code: '783', name: 'Quận 4' },
        { code: '784', name: 'Quận 7' }
    ],
    '48': [ // Đà Nẵng
        { code: '490', name: 'Liên Chiểu' },
        { code: '491', name: 'Thanh Khê' },
        { code: '492', name: 'Hải Châu' },
        { code: '493', name: 'Sơn Trà' },
        { code: '494', name: 'Ngũ Hành Sơn' },
        { code: '495', name: 'Cẩm Lệ' },
        { code: '498', name: 'Hòa Vang' },
        { code: '499', name: 'Hoàng Sa' },
    ],
    '31': [ // Hải Phòng
        { code: '303', name: 'Hồng Bàng' },
        { code: '304', name: 'Ngô Quyền' },
        { code: '305', name: 'Lê Chân' },
        { code: '306', name: 'Hải An' },
        { code: '307', name: 'Kiến An' },
        { code: '308', name: 'Đồ Sơn' },
        { code: '309', name: 'Dương Kinh' },
        { code: '311', name: 'Thuỷ Nguyên' },
        { code: '312', name: 'An Dương' },
        { code: '313', name: 'An Lão' },
        { code: '314', name: 'Kiến Thuỵ' },
        { code: '315', name: 'Tiên Lãng' },
        { code: '316', name: 'Vĩnh Bảo' },
        { code: '317', name: 'Cát Hải' },
        { code: '318', name: 'Bạch Long Vĩ' }
    ],
    '92': [ // Cần Thơ
        { code: '916', name: 'Ninh Kiều' },
        { code: '917', name: 'Ô Môn' },
        { code: '918', name: 'Bình Thuỷ' },
        { code: '919', name: 'Cái Răng' },
        { code: '923', name: 'Thốt Nốt' },
        { code: '924', name: 'Vĩnh Thạnh' },
        { code: '925', name: 'Cờ Đỏ' },
        { code: '926', name: 'Phong Điền' },
        { code: '927', name: 'Thới Lai' }
    ],
    '27': [ // Bắc Ninh
        { code: '256', name: 'TP Bắc Ninh' },
        { code: '258', name: 'Yên Phong' },
        { code: '259', name: 'Quế Võ' },
        { code: '260', name: 'Tiên Du' },
        { code: '261', name: 'TP Từ Sơn' },
        { code: '262', name: 'Thuận Thành' },
        { code: '263', name: 'Gia Bình' },
        { code: '264', name: 'Lương Tài' }
    ],
    '26': [ // Vĩnh Phúc
        { code: '243', name: 'TP Vĩnh Yên' },
        { code: '244', name: 'TP Phúc Yên' },
        { code: '246', name: 'Lập Thạch' },
        { code: '247', name: 'Tam Dương' },
        { code: '248', name: 'Tam Đảo' },
        { code: '249', name: 'Bình Xuyên' },
        { code: '250', name: 'Yên Lạc' },
        { code: '252', name: 'Vĩnh Tường' },
        { code: '253', name: 'Sông Lô' }
    ],
    '25': [ // Phú Thọ
        { code: '228', name: 'TP Việt Trì' },
        { code: '229', name: 'TX Phú Thọ' },
        { code: '231', name: 'Đoan Hùng' },
        { code: '232', name: 'Hạ Hoà' },
        { code: '233', name: 'Thanh Ba' },
        { code: '234', name: 'Phù Ninh' },
        { code: '235', name: 'Yên Lập' },
        { code: '236', name: 'Cẩm Khê' },
        { code: '237', name: 'Tam Nông' },
        { code: '238', name: 'Lâm Thao' },
        { code: '239', name: 'Thanh Sơn' },
        { code: '240', name: 'Thanh Thuỷ' },
        { code: '241', name: 'Tân Sơn' }
    ],
    '22': [ // Quảng Ninh
        { code: '193', name: 'TP Hạ Long' },
        { code: '194', name: 'TP Móng Cái' },
        { code: '195', name: 'TP Cẩm Phả' },
        { code: '196', name: 'TP Uông Bí' },
        { code: '198', name: 'Bình Liêu' },
        { code: '199', name: 'Tiên Yên' },
        { code: '200', name: 'Đầm Hà' },
        { code: '201', name: 'Hải Hà' },
        { code: '202', name: 'Ba Chẽ' },
        { code: '203', name: 'Vân Đồn' },
        { code: '204', name: 'TX Đông Triều' },
        { code: '205', name: 'TX Quảng Yên' },
        { code: '206', name: 'Cô Tô' }
    ],
    '24': [ // Bắc Giang
        { code: '213', name: 'TP Bắc Giang' },
        { code: '215', name: 'Yên Thế' },
        { code: '216', name: 'Tân Yên' },
        { code: '217', name: 'Lạng Giang' },
        { code: '218', name: 'Lục Nam' },
        { code: '219', name: 'Lục Ngạn' },
        { code: '220', name: 'Sơn Động' },
        { code: '221', name: 'Yên Dũng' },
        { code: '222', name: 'Việt Yên' },
        { code: '223', name: 'Hiệp Hòa' }
    ],
    '19': [ // Thái Nguyên
        { code: '164', name: 'TP Thái Nguyên' },
        { code: '165', name: 'TP Sông Công' },
        { code: '167', name: 'Định Hóa' },
        { code: '168', name: 'Phú Lương' },
        { code: '169', name: 'Đồng Hỷ' },
        { code: '170', name: 'Võ Nhai' },
        { code: '171', name: 'Đại Từ' },
        { code: '172', name: 'TX Phổ Yên' },
        { code: '173', name: 'Phú Bình' }
    ],
    '33': [ // Hưng Yên
        { code: '323', name: 'TP Hưng Yên' },
        { code: '325', name: 'Văn Lâm' },
        { code: '326', name: 'Văn Giang' },
        { code: '327', name: 'Yên Mỹ' },
        { code: '328', name: 'TX Mỹ Hào' },
        { code: '329', name: 'Ân Thi' },
        { code: '330', name: 'Khoái Châu' },
        { code: '331', name: 'Kim Động' },
        { code: '332', name: 'Tiên Lữ' },
        { code: '333', name: 'Phù Cừ' }
    ],
    '35': [ // Hà Nam
        { code: '347', name: 'TP Phủ Lý' },
        { code: '349', name: 'TX Duy Tiên' },
        { code: '350', name: 'Kim Bảng' },
        { code: '351', name: 'Thanh Liêm' },
        { code: '352', name: 'Bình Lục' },
        { code: '353', name: 'Lý Nhân' }
    ],
    '36': [ // Nam Định
        { code: '356', name: 'TP Nam Định' },
        { code: '358', name: 'Mỹ Lộc' },
        { code: '359', name: 'Vụ Bản' },
        { code: '360', name: 'Ý Yên' },
        { code: '361', name: 'Nghĩa Hưng' },
        { code: '362', name: 'Nam Trực' },
        { code: '363', name: 'Trực Ninh' },
        { code: '364', name: 'Xuân Trường' },
        { code: '365', name: 'Giao Thủy' },
        { code: '366', name: 'Hải Hậu' }
    ],
    '37': [ // Ninh Bình
        { code: '369', name: 'TP Ninh Bình' },
        { code: '370', name: 'TP Tam Điệp' },
        { code: '372', name: 'Nho Quan' },
        { code: '373', name: 'Gia Viễn' },
        { code: '374', name: 'Hoa Lư' },
        { code: '375', name: 'Yên Khánh' },
        { code: '376', name: 'Kim Sơn' },
        { code: '377', name: 'Yên Mô' }
    ],
    '40': [ // Nghệ An
        { code: '412', name: 'TP Vinh' },
        { code: '413', name: 'TX Cửa Lò' },
        { code: '414', name: 'TX Thái Hoà' },
        { code: '415', name: 'Quế Phong' },
        { code: '416', name: 'Quỳ Châu' },
        { code: '417', name: 'Kỳ Sơn' },
        { code: '418', name: 'Tương Dương' },
        { code: '419', name: 'Nghĩa Đàn' },
        { code: '420', name: 'Quỳ Hợp' },
        { code: '421', name: 'Quỳnh Lưu' },
        { code: '422', name: 'Con Cuông' },
        { code: '423', name: 'Tân Kỳ' },
        { code: '424', name: 'Anh Sơn' },
        { code: '425', name: 'Diễn Châu' },
        { code: '426', name: 'Yên Thành' },
        { code: '427', name: 'Đô Lương' },
        { code: '428', name: 'Thanh Chương' },
        { code: '429', name: 'Nghi Lộc' },
        { code: '430', name: 'Nam Đàn' },
        { code: '431', name: 'Hưng Nguyên' },
        { code: '432', name: 'TX Hoàng Mai' }
    ],
    '75': [ // Đồng Nai
        { code: '731', name: 'TP Biên Hòa' },
        { code: '732', name: 'TP Long Khánh' },
        { code: '734', name: 'Tân Phú' },
        { code: '735', name: 'Vĩnh Cửu' },
        { code: '736', name: 'Định Quán' },
        { code: '737', name: 'Trảng Bom' },
        { code: '738', name: 'Thống Nhất' },
        { code: '739', name: 'Cẩm Mỹ' },
        { code: '740', name: 'Long Thành' },
        { code: '741', name: 'Xuân Lộc' },
        { code: '742', name: 'Nhơn Trạch' }
    ],
    '74': [ // Bình Dương
        { code: '718', name: 'TP Thủ Dầu Một' },
        { code: '719', name: 'Bàu Bàng' },
        { code: '720', name: 'Dầu Tiếng' },
        { code: '721', name: 'TX Bến Cát' },
        { code: '722', name: 'Phú Giáo' },
        { code: '723', name: 'TX Tân Uyên' },
        { code: '724', name: 'TP Dĩ An' },
        { code: '725', name: 'TP Thuận An' },
        { code: '726', name: 'Bắc Tân Uyên' }
    ],
    '72': [ // Tây Ninh
        { code: '703', name: 'TP Tây Ninh' },
        { code: '705', name: 'Tân Biên' },
        { code: '706', name: 'Tân Châu' },
        { code: '707', name: 'Dương Minh Châu' },
        { code: '708', name: 'Châu Thành' },
        { code: '709', name: 'TX Hòa Thành' },
        { code: '710', name: 'Gò Dầu' },
        { code: '711', name: 'Bến Cầu' },
        { code: '712', name: 'TX Trảng Bàng' }
    ],
    '77': [ // Bà Rịa - Vũng Tàu
        { code: '747', name: 'TP Vũng Tàu' },
        { code: '748', name: 'TP Bà Rịa' },
        { code: '750', name: 'Châu Đức' },
        { code: '751', name: 'Xuyên Mộc' },
        { code: '752', name: 'Long Điền' },
        { code: '753', name: 'Đất Đỏ' },
        { code: '754', name: 'TX Phú Mỹ' },
        { code: '755', name: 'Côn Đảo' }
    ]
};

// Helper to get districts (fallback generic if missing)
export const getDistricts = (provinceCode: string) => {
    return DISTRICTS[provinceCode] || [
        { code: 'other', name: 'Quận/Huyện khác' }
    ];
};
