-- ==============================================================================
-- Module: Factory Setup Seed Data
-- Description: Seed data generated by AI for a 60m2 Food Factory Setup 
-- Total Budget: 50,000,000 VND
-- ==============================================================================

-- Xóa dữ liệu cũ nếu có để tránh trùng lặp khi chạy lại
DELETE FROM factory_setup_expenses;
DELETE FROM factory_setup_tasks;

-- 1. Insert Phân công công việc (Tasks)
INSERT INTO factory_setup_tasks (title, description, status, priority, order_index) VALUES
('Khảo sát đo đạc lại mặt bằng 60m2', 'Lên bản vẽ sơ đồ phân khu (Khu nguyên liệu, khu sơ chế, khu chế biến, khu đóng gói, khu thành phẩm)', 'todo', 'urgent', 1),
('Chuẩn bị hồ sơ pháp lý', 'Đăng ký kinh doanh và học lớp tập huấn kiến thức An toàn VSATTP cho nhân sự', 'todo', 'high', 2),
('Xử lý mặt sàn 60m2', 'Vệ sinh bề mặt và sơn Epoxy (hoặc ốp gạch men loại chống trơn trượt) để dễ cọ rửa dầu mỡ và chống đọng nước', 'todo', 'high', 3),
('Lắp rèm nhựa PVC / vách ngăn Panel', 'Phân tách Khu sống (sơ chế, rửa) và Khu chín (chế biến, đóng gói)', 'todo', 'high', 4),
('Cải tạo hệ thống cấp thoát nước', 'Làm hố ga hoặc bẫy mỡ chặn nước thải trước khi ra cống chung', 'todo', 'normal', 5),
('Lắp đặt hệ thống lưới chống côn trùng', 'Lắp tại các cửa sổ, quạt thông gió và cửa đi', 'todo', 'normal', 6),
('Tăng cường đường điện mạ kẽm an toàn', 'Bảo vệ điện chống chập cháy/nước ở các khu vực chế biến/rửa dọn', 'todo', 'high', 7),
('Tìm mua Bàn Inox SUS 304', 'Tối thiểu 2 cái: 1 sơ chế, 1 đóng gói', 'todo', 'normal', 8),
('Tìm mua Bồn rửa công nghiệp Inox', 'Mua/gia công bồn rửa lớn có chân yếm', 'todo', 'normal', 9),
('Nhập trang thiết bị bảo hộ sinh học', 'Khẩu trang, mũ trùm tóc, tạp dề, găng tay thực phẩm', 'todo', 'normal', 10),
('Bố trí tủ thuốc y tế dự phòng & tủ lưu mẫu', 'Tủ lưu mẫu thực phẩm bắt buộc khi kiểm tra VSATTP', 'todo', 'normal', 11),
('Tổng vệ sinh bằng hóa chất sát khuẩn', 'Chạy thử nghiệm khô dây chuyền điện nước', 'todo', 'normal', 12),
('Mời Đoàn kiểm tra thẩm định cơ sở', 'Cấp Giấy Chứng Nhận Cơ Sở Đủ Điều Kiện VSATTP', 'todo', 'high', 13);


-- 2. Insert Dự toán ngân sách (Expenses)
INSERT INTO factory_setup_expenses (item_name, category, amount_expected, amount_actual, status) VALUES
('Cải tạo nền/sàn chống thấm', 'hardware', 12000000, 0, 'pending'),
('Vách ngăn & Rèm PVC', 'hardware', 8000000, 0, 'pending'),
('Bàn & Bồn rửa Inox 304', 'hardware', 12000000, 0, 'pending'),
('Hệ thống cấp thoát nước, điện đèn', 'hardware', 7000000, 0, 'pending'),
('Hệ thống quạt hút thông gió', 'hardware', 4000000, 0, 'pending'),
('Chi phí xin phép VSATTP', 'legal', 5000000, 0, 'pending'),
('Dự phòng phát sinh (thùng rác, pallet)', 'other', 2000000, 0, 'pending');
